version: '3'

services:
  etl:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./:/voldata
    ports:
      - '8088:8088'
    command: tail -f /dev/null
volumes:
  app-vol:
